kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: network-metrics-daemon
  labels:
    app: network-metrics-daemon
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - pods
