apiVersion: v1
kind: Service
metadata:
  name: network-metrics-daemon
  labels:
    app: network-metrics-daemon
spec:
  selector:
    app: network-metrics-daemon
  ports:
    - port: 9091
      targetPort: metrics
      name: metrics
